logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
  file:
    name: UsersApi.log

server:
  port: ${PORT:0}

spring:
  devtools:
    remote:
      restart:
        enabled: true
  application:
    name: UsersApi



eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


management:
  endpoints:
    web:
      exposure:
        include: '*'