server:
  port: 8082

spring:
  application:
    name: MarketiumConfigServer
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eartar/MarketiumConfig
          clone-on-start: true
          default-label: main


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh